spring.application.name=event-processing-engine

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss} %-5level[%X{correlationId}] %msg%n"